### PR TITLE
Added Solarized light/dark themes

### PR DESCRIPTION
**Pull request by beebop-Wiz**

### CODE REVIEW

**Comment by icecube45** [comment]
What version of bootstrap is this theme for - parts runs on 2.2.3 and future versions will break functionality.

**Comment by mm-52tFd** [comment]
will need to update header erb to load the correct stylesheet

**Comment by icecube45** [comment]
@morops this opens us up to the chance of making the loading of styles much more dynamic - I actually forget how I did it originally but it wouldn't be that much work to make it much more dynamic

**Comment by icecube45** [comment]
This issue is now made obsolete with #46 
In addition to more dynamic theme management, solarized is also now a theme DBP will ship with.

**Pull request closed without merging**
